import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const lexend = Lexend({
  variable: "--font-sans",
  subsets: ["latin"],
});

// Self-hosted Illinois Mono (SIL OFL). Files live in ./fonts; see fonts/OFL.txt.
const illinoisMono = localFont({
  src: [
    { path: "./fonts/IllinoisMono-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/IllinoisMono-Italic.ttf", weight: "400", style: "italic" },
    { path: "./fonts/IllinoisMono-Medium.ttf", weight: "500", style: "normal" },
    { path: "./fonts/IllinoisMono-MediumItalic.ttf", weight: "500", style: "italic" },
    { path: "./fonts/IllinoisMono-Bold.ttf", weight: "700", style: "normal" },
    { path: "./fonts/IllinoisMono-BoldItalic.ttf", weight: "700", style: "italic" },
  ],
  variable: "--font-illinois-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lexend.variable} ${illinoisMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
